# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-ec1be05f-7f17-4992-8989-f022be84b3b4";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-ec1be05f-7f17-4992-8989-f022be84b3b4".device =
    "/dev/disk/by-uuid/ec1be05f-7f17-4992-8989-f022be84b3b4";

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-ec1be05f-7f17-4992-8989-f022be84b3b4";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A0F8-F203";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/11d2137a-7b60-43d7-88e7-f93b2b3a3c0f";
    fsType = "btrfs";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/8f212b75-1f01-4b1a-946c-dc1586861c3e"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
